import type { MenuItem } from "../types"

export const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "Minute Burger",
    category: "Sulit Sandwiches",
    price: 89.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "2",
    name: "Black Pepper Burger",
    category: "Big Time Burgers",
    price: 89.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "3",
    name: "Bacon Cheese Burger",
    category: "Big Time Burgers",
    price: 96.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "4",
    name: "Beef Shawarma",
    category: "Big Time Burgers",
    price: 90.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "5",
    name: "Steak Burger",
    category: "Big Time Burgers",
    price: 136.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "6",
    name: "Double Minute Burger",
    category: "Sulit Sandwiches",
    price: 63.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "7",
    name: "Chili Con Cheese Franks",
    category: "Hotdogs",
    price: 94.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "8",
    name: "French Onion Franks",
    category: "Hotdogs",
    price: 92.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  { id: "9", name: "Calamantea", category: "Beverages", price: 24.0, image: "/placeholder.svg?height=120&width=120" },
  { id: "10", name: "Iced Choco", category: "Beverages", price: 23.0, image: "/placeholder.svg?height=120&width=120" },
  {
    id: "11",
    name: "Double Cheesy Burger",
    category: "Big Time Burgers",
    price: 79.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "12",
    name: "Double Chicken Time",
    category: "Chicken Time Sandwiches",
    price: 69.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "13",
    name: "50/50 Veggie Premium Chicken Burger",
    category: "Chicken Time Sandwiches",
    price: 86.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "14",
    name: "Chicken Time",
    category: "Chicken Time Sandwiches",
    price: 50.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "15",
    name: "Roasted Sesame Crispy Chicken Burger",
    category: "Chicken Time Sandwiches",
    price: 96.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "16",
    name: "Chimi-Pesto Burger",
    category: "Big Time Burgers",
    price: 98.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "17",
    name: "Cheesy Burger",
    category: "Big Time Burgers",
    price: 52.0,
    image: "/placeholder.svg?height=120&width=120",
  },
  {
    id: "18",
    name: "Cheesy Nachos",
    category: "Extras/Side Items",
    price: 52.0,
    image: "/placeholder.svg?height=120&width=120",
  },
]

export const categories = [
  "All",
  "Sulit Sandwiches",
  "Big Time Burgers",
  "Chicken Time Sandwiches",
  "Hotdogs",
  "Beverages",
  "Extras/Side Items",
]
